const request = require("supertest");
const { randomUUID } = require("crypto");
const bcrypt = require("bcryptjs");

jest.mock("../src/config/redis", () => require("./support/redis"));
jest.mock("../src/queues/analyticsQueue", () => ({ add: jest.fn(async () => ({ id: "integration-job" })), close: jest.fn(async () => {}) }));

const configured = Boolean(global.integrationDatabaseUrl);
const integration = configured ? describe : describe.skip;

integration(configured ? "dedicated PostgreSQL integration" : "PostgreSQL integration skipped: configure a separate TEST_DATABASE_URL and apply migrations", () => {
  let prisma, app, queue, redis, processAnalyticsJob;
  let owner, stranger, admin;
  const emails = [];
  const password = "integration-only-password";

  async function register(role = "USER") {
    const email = `jest-${randomUUID()}@example.test`;
    emails.push(email);
    const response = await request(app).post("/api/auth/register").send({ name: "Integration Test", email, password }).expect(201);
    let token = response.body.data.token;
    const savedUser = response.body.data.user;
    if (role === "ADMIN") {
      await prisma.user.update({ where: { id: savedUser.id }, data: { role } });
      const login = await request(app).post("/api/auth/login").send({ email, password }).expect(200);
      token = login.body.data.token;
    }
    return { ...savedUser, role, token, authorization: `Bearer ${token}` };
  }
  async function createLink(account = owner, options = {}) {
    const response = await request(app).post("/api/links").set("Authorization", account.authorization)
      .send({ originalUrl: "https://example.com/integration", ...options }).expect(201);
    return response.body.data.link;
  }

  beforeAll(async () => {
    // config/env enforces a distinct database whose name contains a test segment.
    // Never substitute DATABASE_URL, run reset, or clear an existing table.
    process.env.TEST_DATABASE_URL = global.integrationDatabaseUrl;
    const env = require("../src/config/env");
    expect(env.databaseUrl).toBe(global.integrationDatabaseUrl);
    prisma = require("../src/config/database");
    app = require("../src/app");
    queue = require("../src/queues/analyticsQueue");
    redis = require("../src/config/redis");
    ({ processAnalyticsJob } = require("../src/utils/analyticsProcessor"));
    await prisma.$connect();
    owner = await register();
    stranger = await register();
    admin = await register("ADMIN");
  });

  afterAll(async () => {
    if (!prisma) return;
    try {
      // UUID emails were generated by this file, so only our fixture users and
      // their cascading links/clicks can be removed, even in a shared test DB.
      if (emails.length) await prisma.user.deleteMany({ where: { email: { in: emails } } });
    } finally { await prisma.$disconnect(); }
  });

  beforeEach(() => { if (queue) queue.add.mockClear(); });

  test("registration/login/profile store bcrypt hashes and reject duplicate emails", async () => {
    const stored = await prisma.user.findUnique({ where: { id: owner.id } });
    expect(await bcrypt.compare(password, stored.password)).toBe(true);
    expect(stored.password).not.toBe(password);
    const profile = await request(app).get("/api/auth/me").set("Authorization", owner.authorization).expect(200);
    expect(profile.body.data.user).not.toHaveProperty("password");
    await request(app).post("/api/auth/register").send({ name: "Duplicate", email: owner.email, password }).expect(409);
    await request(app).post("/api/auth/login").send({ email: owner.email, password: "wrong-password" }).expect(401);
  });

  test("CRUD persists data, enforces ownership, redacts passwords, and paginates", async () => {
    const target = await createLink(owner, { password: "protected-link-password", title: "Initial" });
    const own = await request(app).get(`/api/links/${target.id}`).set("Authorization", owner.authorization).expect(200);
    expect(own.body.data.link.passwordProtected).toBe(true);
    expect(own.body.data.link).not.toHaveProperty("password");
    for (const [method, suffix] of [["get", ""], ["patch", ""], ["delete", ""], ["post", "/toggle"], ["post", "/qr"], ["get", "/stats"], ["get", "/clicks"], ["get", "/analytics"]]) {
      await request(app)[method](`/api/links/${target.id}${suffix}`).set("Authorization", stranger.authorization)
        .send(method === "patch" ? { title: "Forbidden" } : undefined).expect(404);
    }
    const update = await request(app).patch(`/api/links/${target.id}`).set("Authorization", owner.authorization).send({ title: "Changed" }).expect(200);
    expect(update.body.data.link.title).toBe("Changed");
    const listing = await request(app).get("/api/links?page=1&limit=1").set("Authorization", owner.authorization).expect(200);
    expect(listing.body.data.links).toHaveLength(1);
    expect(listing.body.data.links[0].userId).toBe(owner.id);
    await request(app).delete(`/api/links/${target.id}`).set("Authorization", owner.authorization).expect(200);
    expect(await prisma.link.findUnique({ where: { id: target.id } })).toBeNull();
  });

  test("custom slug uniqueness, password redirects, expiry, and toggles work against persisted links", async () => {
    const target = await createLink(owner, { slug: `int-${randomUUID()}`, password: "protected-link-password" });
    await request(app).post("/api/links").set("Authorization", owner.authorization).send({ originalUrl: "https://example.com", slug: target.slug }).expect(409);
    await request(app).get(`/${target.slug}`).expect(401);
    const verify = await request(app).post(`/${target.slug}/verify`).send({ password: "protected-link-password" }).expect(200);
    await request(app).get(`/${target.slug}`).query({ token: verify.body.data.token }).expect(302);
    await request(app).post(`/api/links/${target.id}/toggle`).set("Authorization", owner.authorization).expect(200);
    await request(app).get(`/${target.slug}`).query({ token: verify.body.data.token }).expect(410);
    await request(app).post(`/api/links/${target.id}/toggle`).set("Authorization", owner.authorization).expect(200);
    await prisma.link.update({ where: { id: target.id }, data: { expiresAt: new Date(Date.now() - 10000) } });
    await redis.del(`link:${target.slug}`);
    await request(app).get(`/${target.slug}`).query({ token: verify.body.data.token }).expect(410);
  });

  test("a redirect job persists one Click on retries and feeds actual SQL analytics", async () => {
    const target = await createLink();
    await request(app).get(`/${target.slug}?utm_source=newsletter&utm_medium=email&utm_campaign=launch`).expect(302);
    const payload = queue.add.mock.calls.at(-1)[1];
    const job = { name: "track-click", id: payload.clickId, data: payload };
    await processAnalyticsJob(job);
    await processAnalyticsJob(job);
    expect(await prisma.click.count({ where: { linkId: target.id } })).toBe(1);
    const saved = await prisma.link.findUnique({ where: { id: target.id } });
    expect(saved.clickCount).toBe(1);
    const stats = await request(app).get(`/api/links/${target.id}/stats`).set("Authorization", owner.authorization).expect(200);
    expect(stats.body.data.stats).toMatchObject({ totalClicks: 1, uniqueVisitors: 1 });
    const clicks = await request(app).get(`/api/links/${target.id}/clicks?page=1&limit=1`).set("Authorization", owner.authorization).expect(200);
    expect(clicks.body.data.clicks[0]).toMatchObject({ utmSource: "newsletter", utmMedium: "email", utmCampaign: "launch" });
    expect(clicks.body.data.pagination).toMatchObject({ total: 1, totalPages: 1 });
    const aggregate = await request(app).get(`/api/links/${target.id}/analytics?days=30`).set("Authorization", owner.authorization).expect(200);
    expect(aggregate.body.data.analytics).toMatchObject({ totalClicks: 1, uniqueVisitors: 1 });
    expect(aggregate.body.data.analytics.byDay).toHaveLength(1);
    expect(aggregate.body.data.analytics.byHour).toHaveLength(1);
    const overview = await request(app).get("/api/analytics/overview?days=30").set("Authorization", owner.authorization).expect(200);
    expect(overview.body.data.overview.totalClicks).toBeGreaterThanOrEqual(1);
  });

  test("maxClicks survives a stale cache after counter eviction", async () => {
    const target = await createLink(owner, { maxClicks: 1 });
    await request(app).get(`/${target.slug}`).expect(302);
    const payload = queue.add.mock.calls.at(-1)[1];
    await processAnalyticsJob({ name: "track-click", id: payload.clickId, data: payload });
    await redis.del(`link:${target.slug}:clicks`);
    await request(app).get(`/${target.slug}`).expect(410);
    expect(queue.add).toHaveBeenCalledTimes(1);
  });

  test("admin includes all owners but never link or user password hashes", async () => {
    await createLink(stranger, { password: "protected-link-password" });
    await request(app).get("/api/admin/links").set("Authorization", owner.authorization).expect(403);
    const response = await request(app).get("/api/admin/links?limit=100").set("Authorization", admin.authorization).expect(200);
    expect(response.body.data.links.some((item) => item.user.id === stranger.id)).toBe(true);
    for (const item of response.body.data.links) {
      expect(item).not.toHaveProperty("password");
      expect(item.user).not.toHaveProperty("password");
    }
  });

  const bullmqTest = global.integrationRedisUrl ? test : test.skip;
  bullmqTest("real BullMQ worker persists a queued click and UTM metadata in PostgreSQL", async () => {
    const Redis = require("ioredis");
    const { Queue, Worker, QueueEvents } = require("bullmq");
    const queueName = `codex-test-${randomUUID()}`;
    const clients = [];
    function connection() {
      const client = new Redis(global.integrationRedisUrl, { maxRetriesPerRequest: null, connectTimeout: 2000, retryStrategy: () => null });
      client.on("error", () => {});
      clients.push(client);
      return client;
    }
    let testQueue, worker, events;
    const workerErrors = [];
    try {
      testQueue = new Queue(queueName, { connection: connection() });
      events = new QueueEvents(queueName, { connection: connection() });
      worker = new Worker(queueName, processAnalyticsJob, { connection: connection(), concurrency: 2 });
      worker.on("error", (error) => workerErrors.push(error));
      events.on("error", (error) => workerErrors.push(error));
      await Promise.all([testQueue.waitUntilReady(), worker.waitUntilReady(), events.waitUntilReady()]);
      const target = await createLink();
      await request(app).get(`/${target.slug}?utm_source=bullmq&utm_medium=worker&utm_campaign=integration`).expect(302);
      const payload = queue.add.mock.calls.at(-1)[1];
      const job = await testQueue.add("track-click", payload, { jobId: payload.clickId, attempts: 3, backoff: { type: "exponential", delay: 50 } });
      const completed = await job.waitUntilFinished(events, 10000);
      expect(completed.tracked).toBe(true);
      const click = await prisma.click.findUnique({ where: { id: payload.clickId } });
      expect(click).toMatchObject({ linkId: target.id, utmSource: "bullmq", utmMedium: "worker", utmCampaign: "integration" });
      expect((await prisma.link.findUnique({ where: { id: target.id } })).clickCount).toBe(1);
      expect(workerErrors).toEqual([]);
    } finally {
      if (worker) await worker.close();
      if (events) await events.close();
      if (testQueue) {
        // This random queue was created above by this test. Its deletion never
        // targets the application's analytics queue or another Redis namespace.
        await testQueue.obliterate({ force: false });
        await testQueue.close();
      }
      for (const client of clients) client.disconnect();
    }
  });
});
